In [88]:
#import numpy as np
from scipy.optimize import minimize
import math

In [241]:
def objective(z):
    p = 0
    for i in range(int(len(z)/3)):
        for j in range(int(len(z)/3)):
            if i != j:
                #equation
                x1 = z[i*3]
                y1 = z[i*3+1]
                d1 = z[i*3+2] 
                x2 = z[j*3]
                y2 = z[j*3+1]
                #depends on angle of first student
                
                x = (x2-x1)*math.cos(d1)+(y2-y1)*math.sin(d1)
                y = (x2-x1)*math.sin(d1)+(y2-y1)*math.cos(d1)
                v1 = ( cube3(x)-cube3(x-6) )
                v2 = ( cube3(y)-cube3(y-6) )
                value = v1 * v2
                p = p + value
    return p

def cube3(num):
    sign = 1
    if num < 0:
        sign = -1
        num = abs(num)
    num = num**(1/3)
    num = num * sign
    return num

In [242]:
students = 10
guess = []
for i in range(students):
    guess.append(i)
    guess.append(i)
    guess.append(0)
print(objective(guess))

311.7047683768908


In [243]:
class_y = 30
class_x = 20
x_bnd = (0,class_x)
y_bnd = (0,class_y)
d_bnd = (0,2*math.pi)
bnds = ()
for i in range(students):
    bnds = bnds + (x_bnd,y_bnd,d_bnd)
#con1 = {'type': 'ineq','fun': constraint1}
#con2 = {'type': 'eq','fun': constraint2}
cons = []

In [244]:
sol = minimize(objective,guess,method='SLSQP',\
                bounds=bnds,constraints=cons)

In [245]:
print(sol)

     fun: 25.325407885107314
     jac: array([-9.15694237e-03,  2.11653709e-02, -4.18150187e-01,  4.40359831e-01,
       -4.82654572e-03,  7.18832016e-02, -4.96819019e-02,  6.15167618e-03,
        2.73089409e-01, -1.73741245e+00, -1.03900433e-02,  1.63004735e+01,
       -1.18951321e-01,  5.57967663e-01,  6.56173944e-01, -4.70271111e-02,
        2.82893181e-02,  8.81390572e-02,  1.48367405e-01,  1.18109496e+01,
        4.69656467e-01,  3.33965063e-01,  6.01530075e-03, -1.36437893e-01,
        1.15676880e-01, -3.97555828e-02,  6.10129833e-01,  9.23859596e-01,
       -1.23755662e+01, -2.56160511e+02])
 message: 'Iteration limit reached'
    nfev: 3286
     nit: 100
    njev: 99
  status: 9
 success: False
       x: array([1.31225737e+01, 0.00000000e+00, 1.20579240e+00, 0.00000000e+00,
       2.54572962e+00, 7.88547320e-01, 1.16879309e+01, 2.23884546e+01,
       8.03540063e-02, 1.99682228e+01, 2.06942183e+01, 6.27732339e+00,
       1.28150843e+00, 6.47033281e-12, 6.12606480e+00, 1.94743786

In [246]:
for i in range(int(len(sol.x)/3)):
    print(sol.x[i*3:(i+1)*3])

[13.12257374  0.          1.2057924 ]
[0.         2.54572962 0.78854732]
[11.68793088 22.3884546   0.08035401]
[19.96822278 20.6942183   6.27732339]
[1.28150843e+00 6.47033281e-12 6.12606480e+00]
[19.4743786  10.26883268  3.22504155]
[ 0.         29.99943669  0.20250185]
[ 0.         20.3952881   2.23152314]
[ 2.86729995 12.66750904  0.03806825]
[20.         30.          6.28318531]
